profile: cover.out

local-prefix: "science.sneaksanddata.com/nexus-configuration-controller"

threshold:
  file: 75
  package: 75
  total: 80
      
exclude:
  paths:
    - \.pb\.go$           # excludes all protobuf generated files
    - ^pkg/generated      # exclude generated code
    - ^pkg/signals        # exclude signal handlers from sample controller
    - hack/*.go           # exclude hack folder
    - main.go             # exclude main file
