alias: ""
controller-config-path: ""
shard-config-path: ""
controller-namespace: "nexus"
log-level: "DEBUG"
workers: "10"
failure-rate-base-delay: "30ms"
failure-rate-max-delay: "5s"
rate-limit-elements-per-second: "50"
rate-limit-elements-burst: "300"
