{{- if .Values.rbac.clusterRole.secretEditor.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.clusteRole.secretEditor" . }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    {{- with .Values.rbac.clusterRole.secretEditor.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.clusterRole.secretEditor.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - verbs:
      - create
      - update
      - patch
      - delete
      - list
      - watch
      - get 
    apiGroups:
      - ""
    resources:
      - events
      - secrets
{{- end }}