apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" $ | nindent 6 }}
  # NCC only supports single replica for now
  replicas: 1
  # The deployment strategy is hardcoded as well until NCC supports HA mode
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "app.labels" $ | nindent 8 }}
      {{- with .Values.additionalAnnotations }}
      annotations:
        deployment/date: {{ now }} # Force redeployment
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ncc
        {{- with .Values.securityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
          image: "{{ include "app.image" . }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            - name: APPLICATION_VERSION
              value: "{{ (default (printf "v%s" .Chart.AppVersion) .Values.image.tag) }}"
            - name: NEXUS__ALIAS
              value: {{ .Values.controller.alias }}
            - name: NEXUS__FAILURE_RATE_BASE_DELAY
              value: {{ .Values.controller.backOffBaseDelay }}
            - name: NEXUS__FAILURE_RATE_MAX_DELAY
              value: {{ .Values.controller.backOffMaxDelay }}
            - name: NEXUS__RATE_LIMIT_ELEMENTS_PER_SECOND
              value: {{ .Values.controller.rateLimitElementsPerSecond | quote }}
            - name: NEXUS__RATE_LIMIT_ELEMENTS_BURST
              value: {{ .Values.controller.rateLimitElementsBurst | quote }}
            - name: NEXUS__WORKERS
              value: {{ .Values.controller.workers | quote }}
            - name: NEXUS__CONTROLLER_NAMESPACE
              value: {{ .Values.controller.namespace }}
            - name: NEXUS__LOG_LEVEL
              value: {{ .Values.controller.logLevel }}
            - name: NEXUS__LOG_LEVEL
              value: {{ .Values.controller.logLevel }}
            - name: NEXUS__SHARD_CONFIG_PATH
              value: {{ .Values.controller.shardsConfigPath }}
            - name: NEXUS__CONTROLLER_CONFIG_PATH
              value: {{ .Values.controller.kubeConfigPath }}              
          {{- if .Values.controller.datadog.enabled }}
            - name: DATADOG__API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.controller.datadog.apiKeySecret | quote }}
                  key: {{ .Values.controller.datadog.apiKeySecretKey | quote }}
            - name: DATADOG__ENDPOINT
              value: {{ .Values.controller.datadog.endpoint | quote }}
            - name: DATADOG__APPLICATION_HOST
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- if .Values.controller.datadog.enableOriginDetection }}
            - name: DD_ENTITY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          {{- end }}
            - name: DATADOG__SERVICE_NAME
              value: {{ .Values.controller.datadog.serviceName }}
            - name: DD_SERVICE
              value: {{ .Values.controller.datadog.serviceName }}
            - name: DD_VERSION
              value: "{{ (default (printf "v%s" .Chart.AppVersion) .Values.image.tag) }}"
            - name: DD_DOGSTATSD_URL
              value: {{ .Values.controller.datadog.statsdUrl | quote }}              
          {{- end }}
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.extraEnvFrom }}
          envFrom:
          {{- with .Values.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
          volumeMounts:
          - name: shards-kube-config
            mountPath: {{ .Values.controller.shardsConfigPath }}
        {{- if .Values.controller.datadog.enabled }}
          - name: dsdsocket
            mountPath: /var/run/datadog
            readOnly: false
        {{- end }}
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      volumes:
        - name: shards-kube-config
          secret:
            secretName: {{ .Values.controller.shardsConfigSecretName }}
       {{- if .Values.controller.datadog.enabled }}
        - name: dsdsocket
          hostPath:
            path: /var/run/datadog/
       {{- end }}
          {{- with .Values.extraVolumes }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}