name: Run tests with coverage
run-name: Validate ${{github.ref_name}} by @${{ github.actor }}

on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]


jobs:
  build:
    name: Validate code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.*'
      - name: Verify dependencies
        run: go mod verify
      - name: Install dependencies
        run: go mod vendor
      - name: Run go vet
        run: go vet ./...
      - name: Build
        run: go build -v ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
      - name: Check Format
        run: gofmt -d ./

      - name: Test
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: Check Coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: science.sneaksanddata.com/nexus-configuration-controller
          threshold-file: 40
          threshold-package: 40
          threshold-total: 50
          
          ## adge is created and committed only for main branch
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          ## name of branch where badges are stored
          ## ideally this should be orphan branch (see below how to create this branch)
          git-branch: badges

      - name: Visualise Coverage
        run: go tool cover -html=cover.out -o=cover.html

      - name: Post Coverage
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.number }}
          body-path: 'cover.html'   
