name: Remove old artifacts
on:
  schedule:
    - cron: '0 12 * * *' # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  remove_old_artifacts:
    name: Remove old artifacts
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    timeout-minutes: 10 # stop the task if it takes longer

    steps:
      - name: Delete old package versions of nexus-configuration-controller
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'nexus-configuration-controller'
          package-type: container
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 100
          ignore-versions: v([0-9]+\.?)+$

      - name: Delete old package versions of helm/nexus-configuration-controller
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'helm/nexus-configuration-controller'
          package-type: container
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 100
          ignore-versions: v([0-9]+\.?)+$